# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fb_id', models.TextField()),
                ('name', models.TextField()),
                ('link', models.URLField()),
                ('gender', models.TextField()),
                ('locale', models.TextField()),
                ('picture_url', models.URLField()),
                ('timezone', models.TextField()),
                ('access_token', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
